In [8]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [9]:
text = [
    """Deep learning is a subset of machine learning that uses artificial neural networks with multiple 
    hidden layers to model complex patterns in data. It is inspired by the structure and function of the 
    human brain, particularly biological neurons and synaptic connections.These deep neural networks 
    automatically learn hierarchical feature representations from raw input data, eliminating the need 
    for manual feature engineering. This makes deep learning especially powerful for high-dimensional 
    data such as images, audio, and text.""",

    """Neural network consists of layers of interconnected nodes or neurons that collaborate to process 
    input data. In a fully connected deep neural network data flows through multiple layers where each 
    neuron performs nonlinear transformations, allowing the model to learn intricate representations of the data.
    In a deep neural network the input layer receives data which passes through hidden layers that transform the 
    data using nonlinear functions. The final output layer generates the model’s prediction.""",

    """Deep learning architectures such as Convolutional Neural Networks (CNNs) and Recurrent Neural Networks 
    (RNNs) are widely used in computer vision and natural language processing. More advanced models like 
    Transformers have further improved performance in sequence modeling tasks.Deep learning requires large 
    datasets, significant computational power, and optimization algorithms like gradient descent with 
    backpropagation. It is widely applied in areas such as speech recognition, autonomous vehicles, medical 
    diagnosis, and recommendation systems."""
]
text

['Deep learning is a subset of machine learning that uses artificial neural networks with multiple \n    hidden layers to model complex patterns in data. It is inspired by the structure and function of the \n    human brain, particularly biological neurons and synaptic connections.These deep neural networks \n    automatically learn hierarchical feature representations from raw input data, eliminating the need \n    for manual feature engineering. This makes deep learning especially powerful for high-dimensional \n    data such as images, audio, and text.',
 'Neural network consists of layers of interconnected nodes or neurons that collaborate to process \n    input data. In a fully connected deep neural network data flows through multiple layers where each \n    neuron performs nonlinear transformations, allowing the model to learn intricate representations of the data.\n    In a deep neural network the input layer receives data which passes through hidden layers that transform the \n

In [10]:
text_words = sum(len(p.split()) for p in text)
print("Total number of words in text:", text_words)

Total number of words in text: 218


In [11]:
#UNIGRAM MODEL
print("UNIGRAM MODEL")

unigram_vectorizer = CountVectorizer(ngram_range=(1, 1),stop_words='english')
X_uni = unigram_vectorizer.fit_transform(text)

print("\nUnigram Vocabulary:")
print(unigram_vectorizer.get_feature_names_out())

print("\nUnigram Matrix:")
print(X_uni.toarray())

uni_similarity = cosine_similarity(X_uni)

print("\nUnigram Cosine Similarity Matrix:")
print(uni_similarity)

UNIGRAM MODEL

Unigram Vocabulary:
['advanced' 'algorithms' 'allowing' 'applied' 'architectures' 'areas'
 'artificial' 'audio' 'automatically' 'autonomous' 'backpropagation'
 'biological' 'brain' 'cnns' 'collaborate' 'complex' 'computational'
 'computer' 'connected' 'connections' 'consists' 'convolutional' 'data'
 'datasets' 'deep' 'descent' 'diagnosis' 'dimensional' 'eliminating'
 'engineering' 'especially' 'feature' 'final' 'flows' 'fully' 'function'
 'functions' 'generates' 'gradient' 'hidden' 'hierarchical' 'high' 'human'
 'images' 'improved' 'input' 'inspired' 'interconnected' 'intricate'
 'language' 'large' 'layer' 'layers' 'learn' 'learning' 'like' 'machine'
 'makes' 'manual' 'medical' 'model' 'modeling' 'models' 'multiple'
 'natural' 'need' 'network' 'networks' 'neural' 'neuron' 'neurons' 'nodes'
 'nonlinear' 'optimization' 'output' 'particularly' 'passes' 'patterns'
 'performance' 'performs' 'power' 'powerful' 'prediction' 'process'
 'processing' 'raw' 'receives' 'recognition'

In [12]:
#BIGRAM MODEL

bigram_vectorizer = CountVectorizer(ngram_range=(2, 2),stop_words='english')
X_bi = bigram_vectorizer.fit_transform(text)

print("\nBigram Vocabulary:")
print(bigram_vectorizer.get_feature_names_out())

print("\nBigram Matrix:")
print(X_bi.toarray())

bi_similarity = cosine_similarity(X_bi)

print("\nBigram Cosine Similarity Matrix:")
print(bi_similarity)


Bigram Vocabulary:
['advanced models' 'algorithms like' 'allowing model' 'applied areas'
 'architectures convolutional' 'areas speech' 'artificial neural'
 'audio text' 'automatically learn' 'autonomous vehicles'
 'backpropagation widely' 'biological neurons' 'brain particularly'
 'cnns recurrent' 'collaborate process' 'complex patterns'
 'computational power' 'computer vision' 'connected deep'
 'connections deep' 'consists layers' 'convolutional neural' 'data deep'
 'data eliminating' 'data flows' 'data fully' 'data images'
 'data inspired' 'data passes' 'data using' 'datasets significant'
 'deep learning' 'deep neural' 'descent backpropagation'
 'diagnosis recommendation' 'dimensional data' 'eliminating need'
 'engineering makes' 'especially powerful' 'feature engineering'
 'feature representations' 'final output' 'flows multiple'
 'fully connected' 'function human' 'functions final' 'generates model'
 'gradient descent' 'hidden layers' 'hierarchical feature'
 'high dimensional' 'hu

In [13]:
#TRIGRAM MODEL

trigram_vectorizer = CountVectorizer(ngram_range=(3, 3),stop_words='english')
X_tri = trigram_vectorizer.fit_transform(text)

print("\nTrigram Vocabulary:")
print(trigram_vectorizer.get_feature_names_out())

print("\nTrigram Matrix:")
print(X_tri.toarray())

tri_similarity = cosine_similarity(X_tri)

print("\nTrigram Cosine Similarity Matrix:")
print(tri_similarity)



Trigram Vocabulary:
['advanced models like' 'algorithms like gradient' 'allowing model learn'
 'applied areas speech' 'architectures convolutional neural'
 'areas speech recognition' 'artificial neural networks'
 'automatically learn hierarchical' 'autonomous vehicles medical'
 'backpropagation widely applied' 'biological neurons synaptic'
 'brain particularly biological' 'cnns recurrent neural'
 'collaborate process input' 'complex patterns data'
 'computational power optimization' 'computer vision natural'
 'connected deep neural' 'connections deep neural'
 'consists layers interconnected' 'convolutional neural networks'
 'data deep neural' 'data eliminating need' 'data flows multiple'
 'data fully connected' 'data images audio' 'data inspired structure'
 'data passes hidden' 'data using nonlinear'
 'datasets significant computational' 'deep learning architectures'
 'deep learning especially' 'deep learning requires'
 'deep learning subset' 'deep neural network' 'deep neural network

In [14]:
#UNIGRAM + BIGRAM MODEL

uni_bi_vectorizer = CountVectorizer(ngram_range=(1, 2),stop_words='english')
X_uni_bi = uni_bi_vectorizer.fit_transform(text)

print("\nUnigram + Bigram Vocabulary:")
print(uni_bi_vectorizer.get_feature_names_out())

print("\nUnigram + Bigram Matrix:")
print(X_uni_bi.toarray())

uni_bi_similarity = cosine_similarity(X_uni_bi)

print("\nUnigram + Bigram Cosine Similarity Matrix:")
print(uni_bi_similarity)


Unigram + Bigram Vocabulary:
['advanced' 'advanced models' 'algorithms' 'algorithms like' 'allowing'
 'allowing model' 'applied' 'applied areas' 'architectures'
 'architectures convolutional' 'areas' 'areas speech' 'artificial'
 'artificial neural' 'audio' 'audio text' 'automatically'
 'automatically learn' 'autonomous' 'autonomous vehicles'
 'backpropagation' 'backpropagation widely' 'biological'
 'biological neurons' 'brain' 'brain particularly' 'cnns' 'cnns recurrent'
 'collaborate' 'collaborate process' 'complex' 'complex patterns'
 'computational' 'computational power' 'computer' 'computer vision'
 'connected' 'connected deep' 'connections' 'connections deep' 'consists'
 'consists layers' 'convolutional' 'convolutional neural' 'data'
 'data deep' 'data eliminating' 'data flows' 'data fully' 'data images'
 'data inspired' 'data passes' 'data using' 'datasets'
 'datasets significant' 'deep' 'deep learning' 'deep neural' 'descent'
 'descent backpropagation' 'diagnosis' 'diagnosis re

In [15]:
#BIGRAM + TRIGRAM MODEL

bi_tri_vectorizer = CountVectorizer(ngram_range=(2, 3),stop_words='english')
X_bi_tri = bi_tri_vectorizer.fit_transform(text)

print("\nBigram + Trigram Vocabulary:")
print(bi_tri_vectorizer.get_feature_names_out())

print("\nBigram + Trigram Matrix:")
print(X_bi_tri.toarray())

bi_tri_similarity = cosine_similarity(X_bi_tri)

print("\nBigram + Trigram Cosine Similarity Matrix:")
print(bi_tri_similarity)


Bigram + Trigram Vocabulary:
['advanced models' 'advanced models like' 'algorithms like'
 'algorithms like gradient' 'allowing model' 'allowing model learn'
 'applied areas' 'applied areas speech' 'architectures convolutional'
 'architectures convolutional neural' 'areas speech'
 'areas speech recognition' 'artificial neural'
 'artificial neural networks' 'audio text' 'automatically learn'
 'automatically learn hierarchical' 'autonomous vehicles'
 'autonomous vehicles medical' 'backpropagation widely'
 'backpropagation widely applied' 'biological neurons'
 'biological neurons synaptic' 'brain particularly'
 'brain particularly biological' 'cnns recurrent' 'cnns recurrent neural'
 'collaborate process' 'collaborate process input' 'complex patterns'
 'complex patterns data' 'computational power'
 'computational power optimization' 'computer vision'
 'computer vision natural' 'connected deep' 'connected deep neural'
 'connections deep' 'connections deep neural' 'consists layers'
 'consis

In [16]:
print("Unigram Cosine Similarity Matrix:")
print(uni_similarity)

print("Bigram Cosine Similarity Matrix:")
print(bi_similarity)

print("Trigram Cosine Similarity Matrix:")
print(tri_similarity)

print("Unigram + Bigram Cosine Similarity Matrix:")
print(uni_bi_similarity)

print("Bigram + Trigram Cosine Similarity Matrix:")
print(bi_tri_similarity)

Unigram Cosine Similarity Matrix:
[[1.         0.44668529 0.28490144]
 [0.44668529 1.         0.12562973]
 [0.28490144 0.12562973 1.        ]]
Bigram Cosine Similarity Matrix:
[[1.         0.07018624 0.14414999]
 [0.07018624 1.         0.        ]
 [0.14414999 0.         1.        ]]
Trigram Cosine Similarity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Unigram + Bigram Cosine Similarity Matrix:
[[1.         0.29757251 0.22256595]
 [0.29757251 1.         0.0731605 ]
 [0.22256595 0.0731605  1.        ]]
Bigram + Trigram Cosine Similarity Matrix:
[[1.         0.03703862 0.07547506]
 [0.03703862 1.         0.        ]
 [0.07547506 0.         1.        ]]
